site_name: SentinelEdge Documentation
site_description: Security product documentation and technical writing portfolio
site_author: Shishir Shreedhar Tambe

repo_name: sentineledge-endpoint-security-docs
repo_url: https://github.com/SHISKEBAB/sentineledge-endpoint-security-docs
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest

nav:
  - Home: docs/index.md
  - About:
      - About This Project: docs/about/project.md
  - Articles:
      - Article 01 - Endpoint Security: docs/articles/2026/Group 1- Security Fundamentals/What is Endpoint Security & Why it matters.md
      - Article 02 - Antivirus vs EDR vs XDR: docs/articles/2026/Group 1- Security Fundamentals/Difference between Antivirus, EDR, and XDR.md
markdown_extensions: 
  - admonition